---
- name: "place configuration file"
  copy: src=app-config/application-{{ spring_active_profile }}.properties dest=/data/{{ application_name }}/application.properties mode=0444
- name: "check if dir exists"
  stat: path=/mnt/videoodyssee-uploader
  register: mountpoint
- name: "mkdir /mnt/videoodyssee-uploader"
  command : sudo mkdir /mnt/energylabel
  when: (mountpoint.stat.isdir is undefined) and (mnt is defined)
- name: "check if dir was made"
  stat: path=/mnt/videoodyssee-uploader
  register: mountpoint
- name: "install nfs-common"
  command : sudo apt-get -y install nfs-common
  when: (mountpoint.stat.exists) and (mnt is defined)
- name: "add nfs folder to fstab"
  shell: grep -q "{{ mnt }} /mnt/videoodyssee-uploader nfs auto,rw,rsize=8192,wsize=8192 0 0" /etc/fstab || echo "{{ mnt }} /mnt/videoodyssee-uploader nfs auto,rw,rsize=8192,wsize=8192 0 0" | sudo tee -a /etc/fstab
  when: (mountpoint.stat.exists) and (mnt is defined)
- name: "mount all"
  command: sudo mount -a
  when: (mountpoint.stat.exists) and (mnt is defined)
